spring:
  datasource:
    url: jdbc:mysql://192.168.2.105/sell?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

